source 'https://cdn.cocoapods.org/'
source 'git@github.com:PhenixRTS/CocoaPodsSpecs.git' # Phenix private repository

platform :ios, '12.0'
use_frameworks!

target 'PhenixClosedCaptionsTests' do
  pod 'PhenixClosedCaptions', :path => '../'
end