source 'https://cdn.cocoapods.org/'
source 'git@github.com:PhenixRTS/CocoaPodsSpecs.git' # Phenix private repository

platform :ios, '13.6'
use_frameworks!
inhibit_all_warnings!

def phenix
  pod 'PhenixSdk', '2023.0.0-e7cae78-20230704T074557589-beta.4'
  pod 'PhenixDebug', :path => '../PhenixDebug'
  pod 'PhenixDeeplink', :path => '../PhenixDeeplink'
  pod 'PhenixClosedCaptions', :path => '../PhenixClosedCaptions'
end

target 'ChannelViewer' do
  phenix
  pod 'SwiftLint', '~> 0.47.1'
end
